import Head from "next/head";
import React from "react";
import { themeClass } from "../../styles/theme.css";
import { Footer } from "../Footer";
import { container, main } from "./layout.css";

export const Layout: React.FunctionComponent<{
  title?: string;
  description?: string;
}> = ({ children, title, description }) => (
  <div className={[themeClass, container].join(" ")}>
    <Head>
      <title>{title ?? "Learn Vanilla Extract"}</title>
      <meta
        name="description"
        content={description ?? "Generated by create next app"}
      />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <main className={main}>{children}</main>

    <Footer />
  </div>
);
