import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import {
  container,
  footer,
  link,
  logo,
  main,
  themeClass,
  title,
} from "../styles/vanilla.css";

const Home: NextPage = () => {
  return (
    <div className={`${themeClass} ${container}`}>
      <Head>
        <title>Learn Vanilla Extract</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={main}>
        <h1 className={title}>
          Learning <a href="https://vanilla-extract.style/">Vanilla Extract!</a>
        </h1>
      </main>

      <footer className={footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
          className={link}
        >
          <span>Powered by</span>
          <span className={logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
        <a
          href="https://vanilla-extract.style/"
          target="_blank"
          rel="noopener noreferrer"
          className={link}
        >
          <span>Styled with</span>
          <span className={logo}>
            <Image
              src="/vanilla-extract.svg"
              alt="Vanilla Extract Logo"
              width={24}
              height={24}
            />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
